Update GPU tests workflow to include additional Python versions and improve Lambda function error handling

diff --git a/.github/workflows/gpu_tests.yml b/.github/workflows/gpu_tests.yml
--- a/.github/workflows/gpu_tests.yml
+++ b/.github/workflows/gpu_tests.yml
@@ -19,15 +19,14 @@ jobs:
     strategy:
       fail-fast: true
       matrix:
-        py-version: [
-           {semantic: '3.10', tox: 'py310'},
-           {semantic: '3.11', tox: 'py311'},
-           {semantic: '3.12', tox: 'py312'},
-           {semantic: '3.13', tox: 'py313'}
-        ]
-    outputs:
-      matrix: ${{ toJson(matrix.py-version) }}
+        py-version: [ {semantic: '3.10', tox: 'py310'} ]
     steps:
+      - name: Generate a token
+        id: generate-token
+        uses: actions/create-github-app-token@v1
+        with:
+          app-id: ${{ vars.APP_ID }}
+          private-key: ${{ secrets.APP_PRIVATE_KEY }}
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
@@ -39,16 +38,20 @@ jobs:
         uses: aws-actions/amazon-ecr-login@v2
       - name: Execute Lambda function
         run: |
-          echo ${{ matrix.py-version }}
+          aws lambda invoke --function-name jit_runner_register_and_create_runner_container  --cli-binary-format raw-in-base64-out --payload '{"github_api_secret": "${{ steps.generate-token.outputs.token }}", "count_container":  1, "container_compute": "XS-GPU", "repository": "${{ github.repository }}" }'  response.json
+
+          if ! grep -q '"statusCode": 200' response.json; then
+            echo "Lambda function failed. statusCode is not 200."
+            exit 1
+          fi
 
   gputest:
     needs: [add-gpu-machine]
+    strategy:
+      matrix:
+        py-version: [ {semantic: '3.10', tox: 'py310'} ]
     name: GPU Tests ${{ matrix.py-version.semantic }}
     runs-on: gpu
-    strategy:
-      fail-fast: true
-      matrix:
-        py-version: ${{ fromJson(needs.add-gpu-machine.outputs.matrix) }}
     steps:
       - name: System Information
         run: |
@@ -60,6 +63,7 @@ jobs:
           df -h
           if [ -x "$(command -v nvidia-smi)" ]; then
             nvidia-smi
+          fi
       - uses: actions/checkout@v4
       - uses: actions/setup-python@v5
         id: setup-python
